apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kajalsec
  name: kajalsec
spec:
  containers:
  - image: 6367400/dockk8s:v1
    name: kajalsec
    env:
    - name: x
      valueFrom:
       secretKeyRef:
        name: kajalsec1
        key: app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
