apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webpod
  name: webpod
spec:
  volumes:
  - name: kajalvol
    configMap:            #volume from configmap
     name: kajalweb  
  containers:
  - image: nginx
    name: webpod
    volumeMounts:
    - name: kajalvol
      mountPath: usr/share/nginx/html
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
